using namespace Microsoft.PowerShell.SHiPS
using module .\PEServer.psm1

# try to model this class based on the JSON file generated by Ravi's
# PEInventoryEx module
[SHiPSProvider(UseCache=$true)]
class PESystem: ShiPSDirectory {
    
    
    # default constructor calls the base constructor here
    # we name the root folder PESystem
    PESystem([string]$Name): base($Name)
    {

    }

    [object[]] GetChildItem()
    {
        $obj = @()
        # fetch the CIM session for the PEDRAC servers
        # IDRAC
        $PEDRACSessions = (& "$Script:CimCmdlets\Get-CIMSession")
        foreach ($PEDRACSession in $PEDRACSessions)
        {
            $obj += [PEServer]::new($PEDRACSession)
        }
        return $obj
    }
    
}
