using namespace Microsoft.PowerShell.SHiPS
using module .\PEServer.psm1
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [ValidateNotNullOrEmpty()]
    [String[]]$iDRACIPs,

    [Parameter(Mandatory)]
    [ValidateNotNullOrEmpty()]
    [pscredential]$iDRACCred
)
    foreach ($ip in $iDRACIPs)
    {
        try {
            Write-Verbose -Message "creating DRACSession for IP $ip "
            New-PEDRACSession -Credential $iDRACCred -IPAddress $ip     
        }
        catch {
            Write-Warning -Message "Opening a DRAC Session for IP $ip failed. It will be skipped."
            Write-Warning -Message "Reason -> $($PSItem.Exception)"
        }
        
    }


# try to model this class based on the JSON file generated by Ravi's
# PEInventoryEx module
[SHiPSProvider(UseCache=$true)]
class PESystem: ShiPSDirectory {
    
    PESystem(): base($this.GetType())
    {
    }
    # default constructor calls the base constructor here
    # we name the root folder PESystem
    PESystem([string]$Name): base($Name)
    {

    }

    [object[]] GetChildItem()
    {
        $obj = @()
        # fetch the CIM session for the PEDRAC servers
        # IDRAC
        $iDRACSessions = @(& "CimCmdlets\Get-CimSession")
        Write-Verbose -Message "Found iDRACSessions -> $($iDRACSessions.Count)" -Verbose
        foreach ($iDRACSession in $iDRACSessions) {
            $obj += [PEServer]::new($iDRACSession)
        }
        return $obj;
    }
    
}
