using namespace Microsoft.PowerShell.SHiPS
using module .\PEServer.psm1

# try to model this class based on the JSON file generated by Ravi's
# PEInventoryEx module
[SHiPSProvider(UseCache=$true)]
class PESystem: ShiPSDirectory {
    
    
    # default constructor calls the base constructor here
    # we name the root folder PESystem
    PESystem([string]$Name): base($Name)
    {

    }

    [object[]]GetChildItem()
    {
        $obj = @()
        # fetch the SCP Json files in the current path and map them
        $Files = @(Get-ChildItem -Path $PSScriptRoot -Filter *.json)
        foreach ($File in $Files)
        {
            $obj += [PEServer]::new($File.BaseName,$File.FullName)
        }
        return $Obj
    }
    
}
